### ISSUE TITLE
Feature request: link back to github repo

### ISSUE THREAD

**Issue by zeroasterisk** [storybooks/react-storybook#254]
I just demoed `react-cdk` for a meetup and got storybook working, and published up to github... all super slick and smooth (thanks!)
- https://github.com/zeroasterisk/react-confirm-button
- https://zeroasterisk.github.io/react-confirm-button/

But I noticed that on the storybook page, there was no way to get back to the github repo.

I think if we are auto-publishing to github pages, it would likely be worthwhile to add a link back to the parent repo automatically...

If not automatic, the ability to add a custom header/sidebar-block/footer might be worthwhile.

**Comment by arunoda** [comment]
Yes. That's a good feature. Basically, we need to provide a way to change the `React Storybook` icon into something user provide.

**Comment by UsulPro** [comment]
closed since this is implemented via [storybook-addon-options](https://github.com/storybooks/storybook-addon-options) now
