### ISSUE TITLE
How do you use react-storybook ?

### ISSUE THREAD

**Issue by ritz078** [storybooks/react-storybook#378]
Would love to know how people use storybook and the particular use case it serves for them. 💻

**Comment by arunoda** [comment]
This is a great question. I'll start why we started this in the first place.

We are using Meteor with React. Earlier it takes a lot of time to happen hot code reloading. Something more than 3 minutes. So, we needed a fix. This was it. We pick ideas from some other existing tools.

Now, we are experimenting this as a design tool where we compare design and the implementation side by side. (Kudos to great ideas from @shilman)

**Comment by UsulPro** [comment]
I use it as start point for developing react components and for deploing live preview in gh-pages ([small example](https://sm-react.github.io/react-smart-textarea/?selectedKind=SmartTextarea&selectedStory=appearance&full=0&down=1&left=1&panelRight=0))
By the way, is there any badge for this purpose to use in readme or elsewhere? What do you think about to have it? I have made such this for myself:

[![Live demo](https://img.shields.io/badge/Live%20Demo-%20Storybook-brightgreen.svg)](https://sm-react.github.io/react-smart-textarea/)

How does it look?  :blush:

**Comment by ritz078** [comment]
Won't it be better if `Live Demo` is `Development` ? Just an idea. or something containing both.
