### ISSUE TITLE
Feature : generate variable props values

### ISSUE THREAD

**Issue by sylvainbannier** [storybooks/react-storybook#500]
When testing a component, I often use long and small texts to check how the component looks in extreme situtations.
Like this : 
![image](https://cloud.githubusercontent.com/assets/452941/18877211/c9f30590-84cc-11e6-9ca3-5379b7f48197.png)

To do that I currently pass props to my component : 

``` js
const eventListItemThesis = {
  researcher: "Researcher's name is very long too",
  category: "this is a long category",
  title: "title very long with a lot of scientific words in it",
  location: "location far far far far away so far away that you'll need 2 lines to display it",
  description: "Short description, but rather long in fact. Maybe a little more text. ",
  date: new Date('2016-09-27'),
  pubDate: new Date('2015-08-20'),
  defenceDate: new Date('2015-08-20')
}
```

It would be very usefull to have a way to generate random texts which lengh could be modified in storybook's menu or via keyboard shorcuts and plug them into my component story with an API like that : 

``` js
const eventListItemThesis = {
  myProp: storybook.randomText
}
```

Do you think it's a good idea ?
Is there already a way to achieve that ?

**Comment by arunoda** [comment]
I think this is a pretty neat feature.
I hope we could build an addon for that as well.

We don't have built in way for this. But I hope we can use some NPM library like [faker](https://www.npmjs.com/package/Faker).

**Comment by sylvainbannier** [comment]
thanks,
[the knobs addon](https://github.com/kadirahq/storybook-addon-knobs) seems  like a good starting point to me. It look like all I need is to feed props with fakerJS. 
I'll give it a try

**Comment by UsulPro** [comment]
@sylvainbannier how are you getting on with this?
Just as an idea, if you want dynamic text: how do you like [this way](https://sm-react.github.io/react-smart-textarea/?selectedKind=SmartTextarea&selectedStory=appearance&full=0&down=1&left=1&panelRight=0) to select the right amount of text by mouse

**Comment by sylvainbannier** [comment]
@UsulPro sorry I don't see the feature you'r talking about. Is there a slider somewhere I didn't noticed ?

**Comment by UsulPro** [comment]
@sylvainbannier just select by mouse some 'lorem ipsum' text at the right column and you will see this amount of text in all textarea elements

**Comment by ndelangen** [comment]
I think is is a good use-case for addon-knobs
