### ISSUE TITLE
Custom page title for the preview window

### ISSUE THREAD

**Issue by rhalff** [storybooks/react-storybook#522]
The iframe currently has a hardcoded title `React Storybook`, which is the same as the parent window.

See: https://github.com/kadirahq/react-storybook/blob/master/src/server/iframe.html.js#L15

This cause redux devtools to show the same instance names:

![storybook](https://cloud.githubusercontent.com/assets/274358/18973788/9ba5928c-869f-11e6-884a-2074077f1862.png)

Perhaps this could be changed to something else, either dynamically with the current story or else something static like Preview.

It works great btw.

**Comment by arunoda** [comment]
Yep. That something we should conside to imple
ent. 
Anyway, why do you the Redux devtools. I am trying to understand the reason behind it.

**Comment by rhalff** [comment]
I've noticed storybook made the redux instance running in the iframe available and it proofs useful to me.

This way containers which are using connect can be tested in isolation and I can verify whether the actions are being dispatched correctly and if the state is updated as intended.

So basically to verify the redux part of the code.

**Comment by arunoda** [comment]
@rhalff Got it.
FYI: We are removing the Redux stuff in out code into a something smaller. We really don't need the power of Redux, since it's not a pretty big UI.

**Comment by rhalff** [comment]
Ok, no problem, I can live with that :-) this issue can be closed then.

**Comment by dptoot** [comment]
Is there anyway we can keep this alive and have the window title for the application configurable within the setOptions plugin?

I see there is an issue open already [here](https://github.com/storybooks/storybook-addon-options/issues/7)
