### ISSUE TITLE
yarn compatibility

### ISSUE THREAD

**Issue by eugene1g** [storybooks/react-storybook#542]
This is not an issue within Storybook, and I'm documenting this here purely for reference/Google-fu.

[Yarn](https://yarnpkg.com/) is a new alternative to NPM-cli from Facebook. There is a known issue (https://github.com/yarnpkg/yarn/issues/620 and https://github.com/yarnpkg/yarn/issues/709) that prevents it from fully handling scoped packages, such as `@kadira/storybook` The package gets installed, but `yarn outdated` command fails with `error https://registry.yarnpkg.com/@kadira/storybook: Not found`.

The Yarn issue has been reported and waiting for a fix, and until it's resolved there might be this minor frustrations for Storybook devs using Yarn.

**Comment by arunoda** [comment]
Yarn is pretty cool. I hope this will get fixed soon.

**Comment by eugene1g** [comment]
The fix has been merged into yarn master with https://github.com/yarnpkg/yarn/pull/1276 so we're just waiting for them to cut a new release

**Comment by eugene1g** [comment]
Yarn [v0.17.0](https://github.com/yarnpkg/yarn/releases/tag/v0.17.0) has been released and it fixes this issue. All good! 🎉🎉

**Comment by arunoda** [comment]
@eugene1g Thanks for keeping us updated on this.
