### ISSUE TITLE
display errors twice with create react app

### ISSUE THREAD

**Issue by sylvainbannier** [storybooks/react-storybook#543]
I freshly installed storybook on create-react-app with `getstorybook`.

here's the brouwser output of `npm start` (CRA) when there's a missing closing tag for instance : 
![image](https://cloud.githubusercontent.com/assets/452941/19313189/f03015fc-9095-11e6-84e0-def2b7dcbe60.png)

And here's the browser output of `npm run storybook` with the same kind of issue : 
![image](https://cloud.githubusercontent.com/assets/452941/19313247/20f0ffda-9096-11e6-8431-3d55260d3297.png)

I see some issues with that output : 
1) the error is displayed twice
2) the text error doesn't wrap (tested in full screen mode too)
3) there's some irrelevant information at the end regarding babel

**Comment by arunoda** [comment]
@roonyh could you look into this?

**Comment by roonyh** [comment]
Sure. Working on it.

**Comment by roonyh** [comment]
I used the [example project](https://github.com/glenjamin/webpack-hot-middleware/tree/master/example) from webpack-hot-middleware and used babel-loader on it. It shows errors in the exact same format.

So this seems like its not fixable from inside storybook. I'll leave this for now to work on some higher priority issues.

We have plans for a error reporting system of our own, like the one create-react-app have. If someone can contribute with anything on something like that, PRs are welcome! :)

**Comment by SpaceK33z** [comment]
Hi, I'm a team member of webpack and I recently debugged an issue that looks very much like this: https://github.com/webpack/webpack/issues/3008. I don't know what package you use exactly to show the error like that, but the package should use `stats.toJson({ errorDetails: false })` to fix it.

**Comment by arunoda** [comment]
Hi @SpaceK33z 
I hope this is coming from `webpack-dev-middleware`.
( I assume you work on that project too)

Let me try to update it.

**Comment by arunoda** [comment]
@SpaceK33z Thanks for the input. 
I added your suggestion and it works.
Sent a PR: https://github.com/glenjamin/webpack-hot-middleware/pull/140

**Comment by arunoda** [comment]
Released the fix as `v2.29.4`.
Thanks everyone.
