### ISSUE TITLE
Story list is empty when loading the storybook inside an IFRAME

### ISSUE THREAD

**Issue by dompuiu** [storybooks/react-storybook#555]
I am using the `HTML Publisher Plugin` from Jenkins to store a static compiled storybook. The `HTML Publisher Plugin` will load the storybook index.html inside an IFRAME. 

It seems that when a storybook is loaded inside the iframe, the available stories are not shown inside the left menu.

This is image showing the problem:
![image](https://cloud.githubusercontent.com/assets/830440/19537551/a4ac2c6a-960d-11e6-9541-ad6131d3b6dc.png)

You can notice that the first story is loaded in the right side of the screen, but the list is empty.

I recently upgrade to the latest version. In v1.x this problem did not exist.

**Comment by arunoda** [comment]
Is there any error on the console?

**Comment by mnmtanish** [comment]
I think it has to do with the way the post msg channel is setup. I'll check this one out

**Comment by dompuiu** [comment]
There is no error on the console.

**Comment by mnmtanish** [comment]
Hi @dompuiu, it should work from `v2.30.1`

**Comment by rexxars** [comment]
I'm using the latest version, but still can't see stories when iframed. The page hosting the iframe is served from a different origin, if that's at all helpful.

**Comment by mnmtanish** [comment]
Thanks @rexxars, I'll check it again

**Comment by rexxars** [comment]
Submitted a PR to [storybook-channel-postmsg](https://github.com/storybooks/storybook-channel-postmsg/pull/8) which fixes this issue.
