### ISSUE TITLE
A new way to load addons via a .json file

### ISSUE THREAD

**Issue by arunoda** [storybooks/react-storybook#604]
With this, we could addon management via a tool easily.
Also, with we could support more features.

* first of all, it'll try to load the given module
* If there's a `/manager.js` file, it'll load it into the manager.
* If there's a `/preview.js` file, it'll load that into the preview.

With this, we could do cool things like adding global decorators without an interaction from the user.

**Comment by ndelangen** [comment]
We could load all addons we know `@storybook/addon-**` and the community developed ones `storybook-addon-**` by reading the `package.json`. I don't think adding another `.json` config file is what user want.
