### ISSUE TITLE
Embedding storybook in iframe hides stories

### ISSUE THREAD

**Issue by joscha** [storybooks/react-storybook#606]
See here: http://aui-cdn.atlassian.com/atlaskit/registry/ak-avatar/latest/index.html on the left side in the panel, there are no stories. When you click on `this version` above it, it opens in a new frame and you can see the stories. This has worked before in an older version of storybook and broke presumably a couple of weeks ago.

**Comment by arunoda** [comment]
Yep. 
This is already reported. 
See: https://github.com/storybooks/react-storybook/issues/555
