### ISSUE TITLE
regex.test is not a function

### ISSUE THREAD

**Issue by kitze** [storybooks/react-storybook#607]
@kadira/storybook v2.29.3

=> Loading custom .babelrc
=> Loading custom webpack config.
/Users/kitze/webdev/personal/x/client/node_modules/@kadira/storybook/dist/server/config.js:102
      return regex.test('my_package.json');
                   ^

TypeError: regex.test is not a function

Got this error with the newest version of storybook. Am I doing something wrong?

**Comment by arunoda** [comment]
Could you send me a copy of your custom webpack config?
This might be related to [this PR.](https://github.com/storybooks/react-storybook/pull/598)

**Comment by kitze** [comment]
I just [submitted a PR](https://github.com/storybooks/react-storybook/pull/608) that fixes it. Btw I'm using [custom-react-scripts](https://www.npmjs.com/package/custom-react-scripts). This is the [webpack config](https://github.com/kitze/create-react-app/blob/master/packages/react-scripts/config/webpack.config.dev.js).

**Comment by arunoda** [comment]
Hmm. I couldn't find the issue by looking at the source. Seems everything fine for me.
Could you try what's coming for the regex variable in that code. I'm curious to what's that?

Also could you tell me how to re-produce with this custom scripts?
So, I could do a test.

**Comment by kitze** [comment]
Oh, I see the problem. This has nothing to do with react-custom-scripts and that webpack.config file.

My webpack config for storybook includes a test that's not a regex, but it's a function. I don't know if you know that "test" accepts both a regex and a function. So that's where it crashes.

**Comment by kitze** [comment]
I just updated the PR with [this commit](https://github.com/storybooks/react-storybook/pull/608/commits/6ef4ad36159c77770065cb7d18ec0a053d510fff). 

The thing here is that if the test is a regex, it should be tested as it was, but if it's a function, it should be also called with the "my_package.json" parameter.
