### ISSUE TITLE
Error message for missing component should be clearer about usage

### ISSUE THREAD

**Issue by rkaramc** [storybooks/react-storybook#609]
Through issue #532 and commit #534, a clearer error message has been added to indicate that a valid component has not been provided in the story.

However, the error message should be clearer and actionable. I misread the current error message as recommending the ()=>{<MyComp>} syntax!!

Current message:
```
Expecting a React element from the story: "basic" of "Game of Life".
Did you forget to return the React element from the story?
Maybe check you are using "() => {<MyComp>}" instead of "() => (<MyComp>)" when defining the story.
```
Proposed message:
```
Expecting a React element from the story: "basic" of "Game of Life".
Did you forget to return the React element from the story?
Use "() => (<MyComp/>)" or "() => { return <MyComp/>; }" when defining the story.
```

Thanks
Rajeev

**Comment by arunoda** [comment]
You are correct.
