### ISSUE TITLE
build-storybook CLI clobbers destination directory

### ISSUE THREAD

**Issue by aeweidne** [storybooks/react-storybook#615]
without the ability to configure that.  those of us writing our storybook to `gh-pages` as well as other information have to use workarounds.

**Comment by arunoda** [comment]
Could you tell me more about this?
I would to do something about this.

**Comment by aeweidne** [comment]
Here are the offending lines, I believe:

![image](https://cloud.githubusercontent.com/assets/6420214/20359449/e7e4af38-abfd-11e6-9476-2c4d51ad96ac.png)

You can see that `shelljs` removes the specified outputDir

**Comment by arunoda** [comment]
That's because we always need to keep a fresh output and do not mix files with the older version.
You should not manually write anything to Storybook's build directory.
