### ISSUE TITLE
UI: Left Panel Search Box unknown dispatch SET_STORY_FILTER "A Title"  

### ISSUE THREAD

**Issue by dfadler** [storybooks/react-storybook#616]
Something appears to be dispatching `SET_STORY_FILTER` with a payload of `{storyFilter: "A Title"}`. I was unable to find a cause in my codebase and after looking through a few of the storybook related repositories I've been unable to locate the string. I did manage to successfully reproduce the issue with the [AirBnB Dates](http://airbnb.io/react-dates) example locally. 

**Local**
![image](https://cloud.githubusercontent.com/assets/728299/20256997/af467f52-a9fb-11e6-905d-870a482dae9c.png)

**Production**
![image](https://cloud.githubusercontent.com/assets/728299/20257009/c1116b98-a9fb-11e6-8b25-e20d683e1c73.png)

**Comment by arunoda** [comment]
That's pretty weird.
I cannot re-produce this.
Searched for the "A Title" text and found nothing.

**Comment by dfadler** [comment]
@arunoda Turns out a browser extension was the culprit and that I shouldn't be writing code at midnight.
