### ISSUE TITLE
[Feature] Get component output(static rendered version)

### ISSUE THREAD

**Issue by mateuspv** [storybooks/react-storybook#617]
Hi, It's possible to get a complete static render version of the current opened component ?
My use case: I deliver plain html samples of components for backend implementation, they don't actually use my components, they look for a specific component and get the html.
Would be nice have a panel "html version"(like action logger and notes), when the user clicks, it renders the component in this section.

Why not just press f12 and get from dev tools: I prefer a clean output with just the current component inside, without any other data.

Let me know if is possible to implement this.

**Comment by evgenykochetkov** [comment]
Yes, I think the implementation should be fairly simple. You can pretty much copy the notes addon from [guide](https://getstorybook.io/docs/react-storybook/addons/writing-addons), but instead of notes it should  display the results of `ReactDOMServer.renderToStaticMarkup(children)`.

**Comment by arunoda** [comment]
@mateuspv We won't do a SSR rendered version of storybook pretty soon. We might do it someday.
You could customize addons as you want.
See: https://getstorybook.io/docs/react-storybook/addons/introduction

**Comment by mateuspv** [comment]
Thanks for de feedback guys...It's on my backlog, but I'm not with too much free time now ^^

**Comment by evgenykochetkov** [comment]
I am preparing a little workshop about storybook for my colleagues, and decided to implement this plugin as an example: https://github.com/evgenykochetkov/react-storybook-addon-static-markup
Enjoy:)

**Comment by arunoda** [comment]
@evgenykochetkov this is cool. 
Add it to here: https://getstorybook.io/docs/react-storybook/addons/addon-gallery
(click on the "EDIT THIS PAGE" link on the top)

**Comment by evgenykochetkov** [comment]
@arunoda, thank you! But are you sure about adding it to addons gallery? I think that this use case is quite unique and the plugin will be useless for 99.9% of people. At least let's see if @mateuspv likes it😄

**Comment by kode8** [comment]
Why would it be useless for 99% of people? I use it so my pattern library is multichannel (html email, ad campaigns, SSR rendered pages). Outputting static html means you can make your Storybook framework agnostic...ie Robust!
