### ISSUE TITLE
Sharing components between projects

### ISSUE THREAD

**Issue by bojandragojevic** [storybooks/react-storybook#618]
I'm interested how to properly share components between projects.

Idea is to use storybook to create component and how than properly to include that in to different projects.

Does someone has nice article or would like to explain ?

Thank you!

**Comment by UsulPro** [comment]
@bojandragojevic!
React components originally created to be [reusable](https://facebook.github.io/react/docs/components-and-props.html)
But if you asking about some storybook specific workflow maybe you'll find interesting the [react-cdk](https://github.com/kadirahq/react-cdk) project! 
This is an excellent storybook based Development Kit which as far as your question can help in the following:
- publish your components to `npm`
- transpille to ES5
- deploy storybook with components to Github Pages

I believe that even if you are not going to be published on `npm`  you like the ability to transpile the component to the `distr` - so you can use it in your other projects.

**Comment by UsulPro** [comment]
I think we can close it
