### ISSUE TITLE
React 15.4.0's performance profiling `react_perf` URL param doesn't work with Storybook

### ISSUE THREAD

**Issue by mnquintana** [storybooks/react-storybook#620]
[React 15.4.0 introduced a way to profile components in the Timeline tab of Chrome DevTools](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html#profiling-components-with-chrome-timeline) with a new URL param, `react_perf` – I tried passing this to the storybook playground, but it doesn't seem to be passed down to the iframe components get loaded in. Is there a way to pass this param?

### Steps to Reproduce
1. Append `?react_perf` to your local storybook server URL (e.g. `localhost:6006/?react_perf`) and visit that URL in a browser
1. Open up DevTools, and record a Timeline of some action you want to profile (e.g. scrolling)

### Expected
The Timeline view contains a `User Timing` label that shows the timeline of each component's updates.

### Actual
There is no `User Timing` label in the timeline view.

Let me know if there's any more info you need! I'd also be happy to submit a PR to add support for this if you can point me in the right direction.

**Comment by arunoda** [comment]
Yep. This is something we need to fix.

**Comment by arunoda** [comment]
@mnquintana I try to do a fix here: #623
Since we render react-components in a iframe, I'm not sure it's getting that or not.

Could you check whether this works or not.
