### ISSUE TITLE
remove default plugins

### ISSUE THREAD

**Issue by jquense** [storybooks/react-storybook#622]
Hi ther and thanks for the excellent tool. I'm running into an issue where the automatically included CaseSensativePlugin conflicts with and breaks other plugins we use in our webpack setup. Specifically because it relys on the `fs` module instead of the exposed compiler filesystem. In any case it prevents my use of storybook while that issue is pending. It would be great if there was a way of completely opting out of any of the default plugins.

**Comment by arunoda** [comment]
Check the [extending default config section](https://getstorybook.io/docs/react-storybook/configurations/custom-webpack-config) of our docs.

<img width="802" alt="screen shot 2016-11-20 at 4 33 31 am" src="https://cloud.githubusercontent.com/assets/50838/20459030/904ae96a-aeda-11e6-9c0d-f453e981fa33.png">

With that, you can access our plugin list and you could remove that.

**Comment by jquense** [comment]
perfect! missed that part
