### ISSUE TITLE
Broken with empty string as the story name

### ISSUE THREAD

**Issue by jpnelson** [storybooks/react-storybook#629]
`storiesOf(name, module);`

I was unlucky because `name` was undefined locally for me, but resolved to `window.name` which is  `window.name === ''`.

the behaviour is that you can't switch stories in the LHS panel.

**Comment by arunoda** [comment]
Hey sorry. I didn't understand.
Could you explain it bit more?

**Comment by arunoda** [comment]
I am closing this issue because of the inactivity. Feel free to reopen this issue with more info.
