### ISSUE TITLE
Add ability to inject middleware so addons can become much smarter

### ISSUE THREAD

**Issue by ndelangen** [storybooks/react-storybook#638]
Currently addons have access to the 'Manager App' and the 'Preview Area'.

Adding an ability to inject custom (express) middleware would open up even more opportunities for creative addon-creators.

These custom middlewares can provide storybook with new features by enabling additional data retrieval for addons.

Some data examples of data:
- unit tests
- package / dependencies version & updates
- package dependency graph
- git & other system integrations

I don't think it's all that hard to implement via `config.js`.

**Comment by mnmtanish** [comment]
Hi @ndelangen 
There's an open pull request for this feature https://github.com/storybooks/react-storybook/pull/435. It does this using a `middleware.js` file. If we use the `config.js` file for middleware, it may add server side code to the javascript bundle it builds for the client.

**Comment by arunoda** [comment]
I think we can close this as we are working on this with #435
