### ISSUE TITLE
Warning about Failed prop type

### ISSUE THREAD

**Issue by tuan23** [storybooks/react-storybook#642]
I'm getting this warning when running storybook:

![storybook failed prop warning](https://cloud.githubusercontent.com/assets/3906505/20953108/11e400a8-bc85-11e6-9fbd-812774171de9.png)

I have tried running different versions but still getting that warning.

Please advise if that is an error in the package or is that something I can fix on my end?

Thanks!

**Comment by janryWang** [comment]
+1

**Comment by mnmtanish** [comment]
Hi @tuan23 and @janryWang 
We fixed this issue [here](https://github.com/storybooks/storybook-ui/pull/66). Please delete the `node_modules` directory and run `npm install` to fix this. If you're using yarn, you'll have to wait until the next release. I'll comment here when it's ready.

**Comment by tuan23** [comment]
Thanks for a quick turn around. Great work with storybook! 👍

Cheers,

Tuan

**Comment by arunoda** [comment]
Awesome. Hope we could close this.
