### ISSUE TITLE
Switching between components `ref` element stop working

### ISSUE THREAD

**Issue by nahumACL** [storybooks/react-storybook#647]
I'm using `ref={ e=>this.element = e}` element to helped me to calculate a position absolute of a menu below a `button/link` when I run the `story` with `focus` in the current story, everything works without problem, but if I switch between components and then click again in that specific `story` the `ref` don't fire again and the element is always is `undefined` and because I'm validating to render the component until `element !== undefined` my component don't get render, I'm attaching a gif image with the behaviour. 

![pillvoterissue](https://cloud.githubusercontent.com/assets/19418590/21116360/26831e2a-c06a-11e6-9ce7-e5f560dd37f2.gif)

a piece of my code
```js
  renderMenu() {
    if (this.$element && this.props.menuList.length > 0 && !this.state.menuCollapse) {
      return (
        <PillMenu
          menuList={this.props.menuList}
          container={this.$element}
          collapse={this.state.menuCollapse}
          onMaskClicked={() => this.setState({ menuCollapse: true })}
          onChange={newValue => this.onChange(newValue)}
        />
      );
    }
    return '';
  }

render() {
  ...
  {this.renderMenu()}
  ...
}
```

any idea what could be happening?

**Comment by arunoda** [comment]
I think we run a fresh component when switching stories.
So, every time it runs with a new instance of your component.

It's really hard for me to tell more about based on this info. If you could create a minimal repo isolating the core problem, I could have a look at it.

**Comment by nahumACL** [comment]
apparently was my mistake, storybook is working correctly again.
