### ISSUE TITLE
Module build failed on fresh install

### ISSUE THREAD

**Issue by WapGeaR** [storybooks/react-storybook#652]
I just install clear version of react-storybook and after command "npm run storybook" I getting error message:
```
ERROR in ./src/stories/index.js
Module build failed: SyntaxError: Unexpected token (8:4)

   6 | storiesOf('Welcome', module)
   7 |   .add('to Storybook', () => (
>  8 |     <Welcome showApp={linkTo('Button')}/>
     |     ^
   9 |   ));
  10 | 
  11 | storiesOf('Button', module)

 @ ./.storybook/config.js 4:2-27
```
Screenshot: http://imgur.com/a/efL5A

**Comment by arunoda** [comment]
I assume, this is something to do with the your root `.babelrc` file.
I'd like to see a sample repo I can see this locally.
So, I can tell you the real problem.

**Comment by WapGeaR** [comment]
@arunoda https://github.com/WapGeaR/create-react-app-antd-template
This repo

**Comment by dagatsoin** [comment]
I have exactly the same issue after after installed storybook in a Meteor app.

**Comment by arunoda** [comment]
@WapGeaR weird.
It's working pretty fine for me.

Can I more info about your system? (OS/NPM/NODE)

**Comment by WapGeaR** [comment]
@arunoda Hi, I found solution. Updating npm to version 4 fix error for me

**Comment by arunoda** [comment]
I assume it's related to an old NPM version and might the OS support.
@dagatsoin could you also upgrade your NPM version and try.

If you get the error again, create a new issue with steps to reproduce.

**Comment by dagatsoin** [comment]
@arunoda just a simple question, how to do you install npm v4?
`$n stable` install node-v7.2.1 and npm@3.10.10

**Comment by arunoda** [comment]
npm i -g npm@4

**Comment by WapGeaR** [comment]
Sometimes it's not working.
If you have errors decrease your node version to 6.x, update npm and after install node 7.x again.

**Comment by dagatsoin** [comment]
actually running:
`node-v7.2.1 and npm@4.0.5`

I do:
```
$ getstorybook -f
$ npm run storybook
```

and got the error of this issue.

It is like that ES5 is not recognized. Is not?

**Comment by dagatsoin** [comment]
Note that I have not put any `.babelrc` in the `.storybook` folder.

**Comment by WapGeaR** [comment]
Try to rm `-rf node_modules` and install it again

**Comment by dagatsoin** [comment]
Found something: 

`=> Loading custom .babelrc` even without any .babelrc into .storybook

Storybook seams to take the one at my project root (used by Meteor)

How to prevent that? (same behavior if I put an empty .babelrc in .storybook to override the root one)

**Comment by arunoda** [comment]
@dagatsoin could you submit a new issue?
Yes we are using .babelrc by default.

**Comment by dagatsoin** [comment]
continue on #657
