### ISSUE TITLE
Add ts and tsx extensions or allow to extend webpack extensions field.

### ISSUE THREAD

**Issue by niba** [storybooks/react-storybook#661]
Hello,
I have the same issue like #562 but with .tsx extension. I can't extend `extensions` field in my custom webpack config and I need that to make it work with my typescript project.

**Comment by sir-marc** [comment]
the referenced issue is fixed?
could you describe your problem with more details? And maybe a way to reproduce.

**Comment by niba** [comment]
The referenced issue is about `JSX` extension. I have problem with `TSX` and `TS` extensions. My project is written in Typescript and all my files are `ts` or `tsx`. I use `ts-loader` loader to produce valid webpack bundle. Storybooks gives my an option to add my custom loader but it doesn't allow to extend `extension` field and without that I can't tell webpack to take `ts` and `tsx` files which are required by `ts-loader` to produce valid component bundle.
Because of that I can't test my components written in Typescript.
There are two ways how to solve it.
1. Add `ts` and `tsx` extension to your base webpack config.
2. Allow users to override `extension` field. (https://github.com/storybooks/react-storybook/blob/master/src/server/config/webpack.config.js#L55)

**Comment by sir-marc** [comment]
Oh sorry, I missed that.
I'm also working with typescript in two projects and both work well with storybook.
My setup:
right next to the config.js file, I have a webpack.config.js file which is basically nothing more than an import export.

```
const webpackConfig = require('./../../webpack.config.js');
module.exports = webpackConfig;
```

in my default webpack.config.js file, i added the extension '.tsx'.
This works just fine for me.

**Comment by niba** [comment]
Yeah, you are right. Totally forgot that you can override entire webpack configuration. Thanks
