### ISSUE TITLE
Add `SBCONFIG_PORT` to documentation

### ISSUE THREAD

**Issue by pierrecholhot** [storybooks/react-storybook#662]
According to the docs, the following is the default method to run the storybook:

```bash
start-storybook -p 5700
```

However, I stumbled upon this undocumented `SBCONFIG_PORT` environment variable in the code while looking for a way to run the storybook remotely on a specific port defined as an ENV_VAR.

It turns out I can start the server this way, without specifying the port with `-p`:

```bash
export SBCONFIG_PORT=5700
start-storybook
```

Is it recommended to use `SBCONFIG_PORT` ? If so, it could be useful to find a mention of this in the docs.

---

As a side note, I edited my init script to use this environment variable only if it's set, otherwise, fallback to the default hardcoded. The reason is to be able to set a different PORT on a remote env without having to EXPORT one locally.

```bash
start-storybook -p ${SBCONFIG_PORT:-5700}
```

**Comment by arunoda** [comment]
`SBCONFIG_PORT` is something we did for some internal tooling.
It's never meant for public use.
We may remove it in the future.
