### ISSUE TITLE
Using storybook for a component library

### ISSUE THREAD

**Issue by davidgomes** [storybooks/react-storybook#665]
If I'm writing my own React Component Library, then I'd rather not have any package.json (and use only Storybook to browse components). Is it possible to have this? If I run `getstorybook` by itself then I get:

```
 • Detecting project type. ✓
    Unsupported Project type. (code: UNDETECTED)
    Visit http://getstorybook.io for more information.
```

If this use case is not supported, let me know please.

**Comment by arunoda** [comment]
You definitely need to have a some `package.json` most of the time. Have a look at here for more info: https://getstorybook.io/docs/react-storybook/basics/slow-start-guide
