### ISSUE TITLE
Do not override provided devtool

### ISSUE THREAD

**Issue by pelotom** [storybooks/react-storybook#666]
It looks like Storybook overrides whatever `devtool` I specify in my `webpack.config.js` with `"eval"`. Unfortunately this breaks line numbers in stack traces when using transpiled languages (in my case TypeScript). Providing a default `devtool` seems fine, but if my config specifies a `devtool` it shouldn't get overridden by storybook.

**Comment by arunoda** [comment]
Yeah! We should do that.
This is the place we need to update: https://github.com/storybooks/react-storybook/blob/master/src/server/config.js#L87

I am happy to take a PR for this.
