### ISSUE TITLE
Module not found when trying to load stylesheet

### ISSUE THREAD

**Issue by DEfusion** [storybooks/react-storybook#667]
My file structure is like so:

```
- app/
-- bundles/
--- FooApp/
---- components/
---- stylesheets/
```

I then have a component like so:

```
// app/bundles/FooApp/components/foo.jsx
import 'fooApp/stylesheets/foo.less'
```

Which gives me the error:

```
Module not found: Error: Cannot resolve 'file' or 'directory' 
/Users/.../app/bundles/FooApp/stylesheets/foo.less 
in /Users/.../app/bundles/FooApp/components
```

This is my storybook `webpack.config.js`

```
const path = require('path')

module.exports = {
  plugins: [],
  module: {
    loaders: [
      {
        test: /\.less$/,
        loaders: [ 'style', 'css', 'less', 'postcss' ],
        include: path.resolve(__dirname, '../')
      }
    ],
  },
  resolve: {
    alias: {
      fooApp: path.resolve('../app/bundles/FooApp'),
      shared: path.resolve('../app/bundles/shared')
    },
  },
};
```

If I move the less alongside the component and do `import './foo.less'` it works, but for other reasons I'd like to keep my structure as it is for now if possible.

**Comment by DEfusion** [comment]
For now I'm doing:

`@import '../stylesheets/foo.less'` in my `components/foo.less` to get this work without moving my stylesheets.

**Comment by arunoda** [comment]
I think you may need to double check on the `fooApp: path.resolve('../app/bundles/FooApp')` path of this.

Anyway, you can always export NODE_PATH=app/bundles/FooApp to import like this:

```js
import 'stylesheets/foo.less'
```

**Comment by DEfusion** [comment]
Thanks for the reply, I changed my alias to:

`fooApp: path.resolve(__dirname, '../app/bundles/FooApp')`

And that worked.
