### ISSUE TITLE
static build is blank

### ISSUE THREAD

**Issue by sir-marc** [storybooks/react-storybook#669]
Storybook is just working well while using the dev server.
but when i want to export it as a static app, i see a blank storybook page. Like the stories are not loaded in.
I'm using version 2.35.2
I get no error message. Nothing. Just a "blank" page (I'm seeing the storybook menu etc but no content)
I'm using a custom webpack config, if this matters.

**Comment by tmeasday** [comment]
Hi @sir-marc, can you provide your custom config? Or better yet a reproduction of the problem with a super-simple repository? That'd be helpful.

**Comment by ndelangen** [comment]
Hey @sir-marc We'd love to help, but as of right now we do not have enough information to help. If you could let us know more about your situation, and maybe give us a reproduction-repo?
