### ISSUE TITLE
Decorator hook for HMR change

### ISSUE THREAD

**Issue by craig-mulligan** [storybooks/react-storybook#681]
I know there are issues applying a decorator on HMR change with this (#284), but I have a case where I need to update the context on each HMR change. (rather than wrapping every story myself)

Basically for [`fela`](https://github.com/rofrischmann/fela) styles to reflect in during HMR you need to find and replace <style> tags on each change. You can see the implementation here: http://fela.js.org/docs/advanced/HotReloading.html

Is there anyway to apply a decorator hook to hmr?

**Comment by wcastand** [comment]
Hi, did you find a solution for using fela with storybook ?
I'm actually trying to implement both storybook and fela on an app at work and get stucked by this :/

Thanks ;)

**Comment by mmintel** [comment]
Sad you closed this issue without providing your solution, i have the same problem :(
