### ISSUE TITLE
Storybook and IE9/10

### ISSUE THREAD

**Issue by jon301** [storybooks/react-storybook#688]
Hi,

I am trying to make storybook work on IE9/10.
Right now, I'm getting the following error : 

```
SCRIPT438: Object doesn't support property or method 'pushState' 
```

* 1st problem
Is there a way to include a polyfill script in storybook ui head tag ? (e.g. https://cdnjs.com/libraries/html5-history-api)
I didn't find in the docs a way to do that properly, so for now I've hardcoded it in the index.html output (but I cannot work with HMR anymore).
This polyfill seems to fix the JS error.

* 2nd problem
With the polyfill above I don't have any JS error, however I always get a blank iframe when I click on any story.

Do you guys have any idea what's going on ?

Thanks for your help !

**Comment by bjankord** [comment]
See #298 for IE10 issues.

**Comment by ndelangen** [comment]
Thank you for reporting this, I'll close this issue in favour of the detailed #298. If you feel you could help and improve things for IE9/10 users that'd be great!
