### ISSUE TITLE
Add allowfullscreen attribute to preview iframe

### ISSUE THREAD

**Issue by heyimalex** [storybooks/react-storybook#689]
I'm working on a component that may go fullscreen using the [browser's fullscreen api](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API). While running the component inside storybook, all attempts to go fullscreen fail and this warning is displayed in the console:

> Request for fullscreen was denied because at least one of the document’s containing elements is not an iframe or does not have an “allowfullscreen” attribute.

The fix should be as easy as adding the [`allowfullscreen`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) attribute to the preview iframe, which I believe is created in [`src/client/manager/preview.js`](https://github.com/storybooks/react-storybook/blob/master/src/client/manager/preview.js#L25).

It's a one line change, and tbh I mostly just don't want to go through installing. But if you want I can make a PR. Temporary fix for anyone running into the same issue, add this to your story:

```javascript
window.parent.document.getElementById('storybook-preview-iframe').setAttribute('allowfullscreen', '');
```

**Comment by ndelangen** [comment]
PR is very much welcome! Thank you!
