### ISSUE TITLE
Easier way of adding a font?

### ISSUE THREAD

**Issue by reggi** [storybooks/react-storybook#709]
Looking for an easier way to add a font, I got this working, but it's not very obvious how this works.

> head.html

```html
<style type="text/css" media="screen, print">
  @font-face {
    font-family: "FontAwesome";
    src: url("/Fonts/FontAwesome.ttf");
  }
</style>
```

Then my start script needed:

```
start-storybook -p 9001 -c .storybook -s ./node_modules/react-native-vector-icons
```

**Comment by NitroBAY** [comment]
I think -s tells storybook that if there's a request, such as `url("/Fonts/FontAwesome.ttf");`, then it searches in the one or the multiple folders passed in the `-s` argument.
Here you passed `./node_modules/react-native-vector-icons` in the -s argument so storybook is looking in this folder when the css asks for `/Fonts/FontAwesome.ttf`.

**Comment by reggi** [comment]
@NitroBAY `-s` allows the passed in folder to serve static files, I get that.

The code above works. I just desire a better way.

**Comment by ndelangen** [comment]
You could use custom middleware to serve it.
https://github.com/storybooks/react-storybook/pull/435#issuecomment-264813688

https://github.com/storybooks/react-storybook/blob/master/src/server/middleware.js#L35


Let me know if you need any more help?

**Comment by OKNoah** [comment]
> You could use custom middleware to serve it.
> [#435 (comment)](https://github.com/storybooks/storybook/pull/435#issuecomment-264813688)
> 
> https://github.com/storybooks/react-storybook/blob/master/src/server/middleware.js#L35
> 
> Let me know if you need any more help?

Dead link btw
