### ISSUE TITLE
build-storybook: cannot create property mappings

### ISSUE THREAD

**Issue by florian-bd** [storybooks/react-storybook#716]
I recently enabled webpack full-control mode.

```
module.exports = function(storybookConfig) {
    const fullConfig = Object.assign(storybookConfig, devConfig, {
        entry: storybookConfig.entry,
        output: storybookConfig.output,
        plugins: storybookConfig.plugins.concat(devConfig.plugins),
        module: Object.assign(storybookConfig, {
            loaders: storybookConfig.module.loaders.concat(
                devConfig.module.loaders
            )
        }),
        resolve: Object.assign(devConfig.resolve, storybookConfig.resolve, {
            alias: Object.assign(
                devConfig.resolve.alias,
                storybookConfig.resolve.alias
            )
        })
    });
    // otherwise mappings error https://github.com/babel/babel-loader/issues/390
    delete fullConfig.devtool;
    return fullConfig;
};
```

I had the following issue with start-storybook:
https://github.com/babel/babel-loader/issues/390

I solved it by removing devtool from the webpack config.

But I still have the issue when running build-storybook.

Any idea why?

**Comment by 2WheelCoder** [comment]
I had the same issue and fixed it by removing the `react-hot` loader before the babel loader. Not sure if you have any loaders before babel in your webpack config, but that seemed to be the issue for me. `react-hot` in particular is not needed when running `build-storybook`.

**Comment by florian-bd** [comment]
I had to remove ```react-hot```as you said, and also ```webpack/hot/only-dev-server``` in my entry point
@2WheelCoder thank you for the help!
