### ISSUE TITLE
Ignore stories folder when testing

### ISSUE THREAD

**Issue by dclawson** [storybooks/react-storybook#725]
How do you ignore the `src/stories` directory when running a --coverage test?

I am using a `create-react-app` base and have tried the following in my package.json

```json
"jest": {
  "collectCoverageFrom": [
    "src/**/*.{js,jsx}",
    "!<rootDir>/node_modules/",
    "!<rootDir>/src/stories/"
  ]
}
```

**Comment by tmeasday** [comment]
It looks like you can't pass options to jest via that mechanism in CRA (https://github.com/facebookincubator/create-react-app/issues/922).

You can pass an argument to jest on the commandline though:

```
npm test -- --coverage --collectCoverageFrom='["src/**/*.{js,jsx}","!src/**/stories/*"]'
```

Do you think we should add some documentation about this?

**Comment by dclawson** [comment]
Thanks @tmeasday.

Yes, I think it would be helpful for --coverage tests.
