### ISSUE TITLE
ES6 in webpack configuration file

### ISSUE THREAD

**Issue by vinhlh** [storybooks/react-storybook#726]
Currently, I had an existing ES6 webpack config file. Then I can't load alias rules to react-storybook.
Do we have any solution for this?

**Comment by vinhlh** [comment]
is duplicated with https://github.com/storybooks/react-storybook/issues/155

**Comment by ndelangen** [comment]
Thank you!, I'd love to do this, can we close this issue so there's no duplicate? The other issue has more detailed information in it.
