### ISSUE TITLE
Fails to load in Safari

### ISSUE THREAD

**Issue by philcockfield** [storybooks/react-storybook#727]
Storybook Version:

        "@kadira/storybook": "^2.35.3",
        "@kadira/storybook-addon-knobs": "^1.7.1",

Safari version: `10.0.3 (12602.4.8)`

![image](https://cloud.githubusercontent.com/assets/185555/24129373/23d7d58c-0e47-11e7-95f6-3d787cf17ce2.png)

Safari console:

![image](https://cloud.githubusercontent.com/assets/185555/24129419/7baf6a68-0e47-11e7-94f5-ea5b9f8411df.png)

**Comment by rafales** [comment]
Do you have storybook-host installed? Same thing happen to me today. I just got rid of storybook-host.

**Comment by philcockfield** [comment]
Oh heck! `storybook-host` - I'll take a look at that.  thanks @rafales

**Comment by rafales** [comment]
@philcockfield Haha, didn't notice it's your package :D

**Comment by ndelangen** [comment]
Is this something we need to take a look at?

**Comment by rafales** [comment]
@ndelangen I don't know. I wasn't able to debug it as there was some problem with source maps for `host.tsx` and safari refused to display anything useful.

**Comment by tmeasday** [comment]
Sounds like maybe an issue with `storybook-host` rather than storybook? Should we close this?

**Comment by tmeasday** [comment]
I think maybe I'll just close it, @philcockfield (hi!) let us know if we should reopen.
