### ISSUE TITLE
An error occurred while installing dependencies

### ISSUE THREAD

**Issue by kaytrance** [storybooks/react-storybook#728]
I am following the guide, but I am stuck on this error:
````
 getstorybook - the simplest way to add a storybook to your project.

 • Detecting project type. ✓
 • Adding storybook support to your "React" app. ✓
 • Preparing to install dependencies. ✓


 • Installing dependencies. ✖

     An error occurred while installing dependencies.
````

I have node 6.9.2 and npm 3.10.8 installed and working properly. What may be the reason then?

**Comment by boyhagemann** [comment]
Have the same issue! I am on windows with node 6.9.1 and npm 3.10.8.

**Comment by UsulPro** [comment]
@kaytrance @boyhagemann 
https://github.com/storybooks/react-storybook/issues/628#issuecomment-263037880

**Comment by oniseijin** [comment]
You get this if you have any internal package issue. I had the same, and it was due to a proxy registry that could not handle @kadira group for some reason. Run getstorybook first, and then run npm install, and you might get more specific error.

**Comment by boyhagemann** [comment]
Thanks, that helped and got it working. Thanks guys!

**Comment by ndelangen** [comment]
Thank for the help @oniseijin !

**Comment by kuzzmi** [comment]
I've just installed getstorybook and have the same issue. No proxies, nothing odd in my setup.

```
> npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

> getstorybook -f

 getstorybook - the simplest way to add a storybook to your project.

 • Detecting project type. ✓
 • Adding storybook support to your "Webpack React" app. ✓
 • Preparing to install dependencies. ✓


 • Installing dependencies. ✖

     An error occurred while installing dependencies.
```

**Comment by veerjainATgmail** [comment]
was getting the above error.. later I tried, 

npm i -g @storybook/cli
cd my-react-app
getstorybook

it worked..

**Comment by Karaca7** [comment]
I was getting the same error on storybook, I was trying to install with pnpm instead I deleted node_modules and package-lock.json file. I installed all dependecie with npm and then I solved the problem by install npx storybook init
