### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by niklaskorz** [storybooks/react-storybook#731]
As Webpack 2 is gaining more and more traction, I am concerned at the lack of development this project has experienced in the last few months.

So I am honestly asking: Is this project dead, and has Kadira lost interest in its future development?

**Comment by marc-rutkowski** [comment]
@niklaskorz, about Kadira, sadly : https://voice.kadira.io/kadira-shutting-down-7d35994db85d#.e7njmzfm7
This probably explains the lose of interest... :(

**Comment by niklaskorz** [comment]
Sad to here that

**Comment by moimikey** [comment]
well at least give people contributor access... this is quite frustrating.

**Comment by edgesoft** [comment]
@arunoda Is this true?

**Comment by augbog** [comment]
Sad to hear about this and thanks for making an issue to bring a little more awareness.

I do have to agree with @moimikey it would be nice if there were some people who could be given contributor access to maintain this project -- lots of people still use it and I feel that's the whole reason this is open source.

**Comment by Vanuan** [comment]
Are there any alternatives? Looks similar to http://react-styleguidist.js.org/

**Comment by sapegin** [comment]
@Vanuan We’re going to release a new major version this week that should improve first-time experience ;-)

**Comment by gregorskii** [comment]
Sad to hear about this. Seems like the community really likes this product. Would be great to see it treated as OSS (detach from Kadira namespace) with contributors.

Cheers

**Comment by gaearon** [comment]
Would any of you be interested in taking over the maintenance and reviewing PRs?

**Comment by Vinnl** [comment]
@gaearon There's an offer here: https://github.com/storybooks/react-storybook/pull/637#issuecomment-289605818

**Comment by UsulPro** [comment]
@gaearon I'd like to join this team and help to maintain Storybook if it's possible!

**Comment by ndelangen** [comment]
I'm interested in helping maintain this as well

**Comment by mthuret** [comment]
Interested as well. I really think this tool is really polyvalent and very useful. It would be sad if this was trashed, for both storybook but also all the addons project that already exists today and add a big plus.

**Comment by arunoda** [comment]
Guys, sorry for not following up.
With the recent developments, I had to take priorities on other projects. And I'm no longer actively using Storybook.

So, it's kind a hard for me to maintain this project. (And some other tools related)
I hope @mnmtanish is taking care of react-native storybook well.

But I need help from others.
Thanks @UsulPro  @ndelangen @mthuret for coming forward.

Here's what we can do:

* I'll make you guys as admins
* Let's do a release of storybook under storybook namespace or without any namespace. 
* Then let's merge PRs and do any development.
* I'll do a blog post on the new changes asking more help.

I won't be able to spend more time on Storybook related code, but I could explain some of the unfamilar code and some of the decision we made.

What do you guys think about this plan?

**Comment by lluia** [comment]
@arunoda I'm happy to help maintain Storybook as well, I think it has a lot of potential 🙃

**Comment by alloy** [comment]
@arunoda Same, I’d like to help as well.

**Comment by edgesoft** [comment]
@arunoda Same here

**Comment by ndelangen** [comment]
I'll try to review PR's as much as possible and am committed to making storybook webpack 2 compatible.

**Comment by xDae** [comment]
Im also interested in collaborate/be part of the project maintenain

**Comment by majapw** [comment]
@arunoda I would also be interested in maintaining this project! :) It's been a great help to us, and I'd love to contribute back.

**Comment by ndelangen** [comment]
Hey thanks everyone for their interest in joining in to help this project! ❤️ 

Right now I don't feel completely comfortable just yet to add people before talking to the others. Please com join in on slack: https://storybooks.slack.com/ to talk about becoming a fellow maintainer, or post in this thread.

And of course if you want to help, you can:
- review PR's, 
- expand your PR's with tests, screenshots, anything to make it easier to understand / review / approve
- fix issues and submit a PR

I'd be happy to add more people, but like I said I just don't feel comfortable making that decision alone.
@lluia @alloy @edgesoft @xDae @majapw

Does anyone object to me closing this issue? 😀

**Comment by edgesoft** [comment]
@ndelangen Perfekt! Thanks!

**Comment by augbog** [comment]
Thank you for pushing this forward :) Looking forward to seeing more great work done on this project 🎉

**Comment by tmeasday** [comment]
Hey @ndelangen I'm keen to help out also; it looks like I need a kadira.io email to join that slack, am I reading that wrong?

**Comment by ndelangen** [comment]
@tmeasday You should be able to request access for any email-address. I'm super confused, because I tried in incognito-mode just now but wasn't able to 😖 . Anyway what I was able to do was invite your public email-address shown on github.

**Comment by niklaskorz** [comment]
@ndelangen @arunoda Really happy to see that my issue actually got attention. Thanks to all of you! 💯

**Comment by xDae** [comment]
@ndelangen I also tried to join to slack channel, but same, its looks like only ..@kadira.io emails can access.

there's an option in slack config to remove email restriction

**Comment by ndelangen** [comment]
I've asked for admin right on the slack team to remove the `@kadira.com` restriction. Until then, send me your email somehow and I'll invite you.

**Comment by bhoomit** [comment]
Would love to help out :)

**Comment by pke** [comment]
Writing stories in its own DSL never convinced me when I can have a simple markdown document like with http://react-styleguidist.js.org

But kudos to the project owners here to keep the project alive and open it up for maintenance.

**Comment by ndelangen** [comment]
Apparently it's impossible to just open your slack team for anyone wanting to join ☹️ .
And it's also not allowed to just add a load of common domain names 😠 

So I guess people need to be invited.
So whomever want to join the slack team, just ask!

**Comment by alloy** [comment]
@ndelangen Once that becomes a burden it’s common to use a tiny app for that so people can self-invite. There’s plenty of options, an (untested) example is https://github.com/rauchg/slackin

**Comment by pke** [comment]
@ndelangen Why use slack then? Use a free, unlimited alternative like discord, or god forbid IRC?

**Comment by niklaskorz** [comment]
Discord is perfect for this. Or ask the reactiflux community to open a channel for Storybook.
https://www.reactiflux.com/

**Comment by ndelangen** [comment]
I'm holding Discord in mind, thanks for suggesting it!

**Comment by dtschust** [comment]
Echoing @alloy 's comment, [slackin](https://github.com/rauchg/slackin) is used by a ton of open source projects to make self-invite slack communities. It uses `now` and is really quick to set up. Feel free to reach out if you'd like any support setting it up 👍

**Comment by bernard-lin** [comment]
@ndelangen Would also love to join in on the fun! My email is bernardlin12@gmail.com. Thanks!

**Comment by VladShcherbin** [comment]
@ndelangen slack is absolute shit for communities, there are much better options - discord / gitter.

**Comment by idkjs** [comment]
Moi aussi. J'aimerais aider!

**Comment by arunoda** [comment]
Guys, we've a slack-in setup here: https://storybooks-slackin.herokuapp.com/

**Comment by theinterned** [comment]
Great! We use Storybook heavily @nulogy.  I'm definitely interested in contributing!
