### ISSUE TITLE
Issue triage guidelines

### ISSUE THREAD

**Issue by tmeasday** [storybooks/react-storybook#733]
Given a variety of contributors, it might be a good idea to put together a basic algorithm for issue triage (and decide on a set of labels, etc). 

Meteor's [issueTriage.md](https://github.com/meteor/meteor/blob/devel/IssueTriage.md) is probably more complicated than what is needed here, but helped in guiding community members to get the number of open issues down from 1000+ and growing to around 600 (a major achievement, let me tell you!), so could be worth looking at for ideas.

So maybe it's best to start with some decisions. I'll post them as separate comments so folks can respond with their opinions.

**Comment by tmeasday** [comment]
Do we want people to ask questions / ask for guidance in issues?

**Comment by tmeasday** [comment]
Do we want people to open issues for permission/advice before creating PRs for new features?

**Comment by tmeasday** [comment]
[If no mono-repo] - do we want to be pedantic about which repo people open issues on?

**Comment by ndelangen** [comment]
I think it's way to complex to keep track of issues across many repo's. 1 of the reasons I'm in favour of a mono-repo.

**Comment by ndelangen** [comment]
I think any well-written PR should be enough, no need to write a issue first if someone proposes a fix or new feature.

**Comment by ndelangen** [comment]
@tmeasday Anything actionable from this issue? How would you like to add this?

**Comment by tmeasday** [comment]
I'd like to add some simple triage guidelines to the contributing.md file.
I can have a go at a pr

**Comment by tmeasday** [comment]
See https://github.com/storybooks/react-storybook/pull/748
