### ISSUE TITLE
object-hash warns about pre-built JS

### ISSUE THREAD

**Issue by Donaldini** [storybooks/react-storybook#745]
Recently i've been getting the following warning:

```
WARNING in ./~/object-hash/dist/object_hash.js
Critical dependencies:
1:383-390 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/object-hash/dist/object_hash.js 1:383-390
```

Currently using **Storybook 2.35.3**

Could be that it is unrelated, but i'm only getting this in my Storybook.

**Comment by ndelangen** [comment]
Sounds like a webpack configuration problem:
https://github.com/webpack/webpack/issues/1617

Do you have a custom webpack configuration?

**Comment by benediktvaldez** [comment]
I think there is a way around this. You could in theory try something like this in your webpack config, except instead of localforage, target the script in question. (Sorry, writing this on my phone 🙃otherwise I'd test it myself to make sure it works)

‘‘‘ 
  module: {
    noParse: /node_modules\/localforage\/dist\/localforage.js/
}
…
‘‘‘

**Comment by Donaldini** [comment]
That seems to have done the trick, thanks!
