### ISSUE TITLE
Unable to load google font via link tag

### ISSUE THREAD

**Issue by qualitydixon** [storybooks/react-storybook#750]
Hi! I'm really enjoying using this library but I'm having a small issue loading fonts. In my project I load open sans from google fonts via a `link` tag in `head`. From the docs it seems like putting the same link tag in `head.html` should work. Is there anything else I need to do to load an external font? Thanks for the help!

**Comment by benediktvaldez** [comment]
Hey @qualitydixon 

Is your project on a public repo, or could you perhaps show us what your config and head.html looks like?

**Comment by qualitydixon** [comment]
Thanks for the reply! I can make a public repo tomorrow. In the meantime, my `head.html` is just one line:
```
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet" type="text/css" />
```

And my `config.js` is this:

```
import { configure } from '@kadira/storybook';

function loadStories() {
  require('../stories');
}

configure(loadStories, module);
```

Am I missing something?

**Comment by qualitydixon** [comment]
The issue was with how I apply fonts on a project level so that in the context of storybook there were not applied. Thanks for the help.

**Comment by avidrucker** [comment]
@qualitydixon Can you share how you resolved the issue? I'm experiencing the same challenge of applying a webfont to my storybook components.

**Comment by tihuan** [comment]
I know this thread is 3 years old, but for completeness, check out: https://storybook.js.org/docs/react/configure/story-rendering#adding-to-head

> If you need to add extra elements to the head of the preview iframe, for instance to load static stylesheets, font files, or similar, you can create a file called .storybook/preview-head.html and add tags like this:

```html
<!-- .storybook/preview-head.html -->

<!-- Pull in static files served from your Static director or the internet -->
<link rel=”preload” href=”your/font” />
<!-- Or you can load custom head-tag JavaScript: -->
<script src="https://use.typekit.net/xxxyyy.js"></script>
<script>try{ Typekit.load(); } catch(e){ }</script>
```

**Comment by NurfitraPujo** [comment]
this worked for me, thanks @tihuan
