### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by garmjs** [storybooks/react-storybook#752]
I'm having problem with CPU as soon as i start `storybook`, is anyone else facing same problem

![screen shot 2017-04-09 at 7 00 55 pm](https://cloud.githubusercontent.com/assets/5017156/24839251/29de2fc0-1d57-11e7-9248-0606912b819f.png)

```
Armends-MBP:dropdown:% node -v
v7.8.0
Armends-MBP:dropdown:%
```

```
@kadira/storybook ^2.21.0
```

**Comment by garmjs** [comment]
The issue happends only if there is any error in components

**Comment by tmeasday** [comment]
Hi @garmjs have you seen it with a simple storybook, maybe one created like so: https://github.com/storybooks/react-storybook/blob/master/CONTRIBUTING.md#reproductions

Starting small may help you/us figure out what it is that's causing it.

**Comment by garmjs** [comment]
Hi @tmeasday,

It looks like its not happens with `create-react-app`, i will investigate this further, as soon as i find something i will push.

for now i'm going to close this issue and open if needed.

**Comment by samkelleher** [comment]
I know this is closed, but following updating to storybook 3.0.0 from 2, the node process for storybook now sits at 100%. Not sure where to begin debugging this.

```
> start-storybook -s ./src -p 9001 -c .storybook

@storybook/react v3.0.0

=> Loading static files from: /src .
=> Loading custom .babelrc
=> Loading custom addons config.
=> Loading custom webpack config (extending mode).
Storybook started on => http://localhost:9001/
```

**Comment by shilman** [comment]
@samkelleher @garmjs do either of you have a public repro? i'd love to take a look!

**Comment by samkelleher** [comment]
@shilman it's a work repo, but I could post the content of the `.storybook` dir that has the custom webpack config. What I'm going to do however is remove all the stories to see what happens, if the CPU useage goes away, gradually adds the stories back in to see if its a specific story.

If the usage does not go away, I'll try again by removing the custom configs.

**Comment by tmeasday** [comment]
@samkelleher did you ever discover anything here?

**Comment by Hypnosphi** [comment]
Such problems are usually solved by adding `fsevents` to `optionalDependencies`

**Comment by felixjung** [comment]
I'm also seeing pretty high CPU usage on my machine. Will have to investigate some more.

**Comment by berkaey** [comment]
me too with a empty storybook

**Comment by felixjung** [comment]
My issues went away after simply deleting `node_modules` and reinstalling in my project.

**Comment by morgs32** [comment]
@shilman I've produced a public repo / repro: https://github.com/morgs32/my-workspace
It may be specific to using yarn workspaces. Should we reopen or move to new issue?

**Comment by morgs32** [comment]
Resolved my issue.  
```
 "workspaces": {
    "packages": [
      "app1"
    ],
    "nohoist": [
      "**/@storybook",
      "**/@storybook/**",
      "**/webpack",
      "**/webpack/**",
      "**/webpack**",
      "**/webpack**/**",
      "**/babel-jest"
    ]
  },
```

Which I thought I had to do because earlier it was looking for all the `.storybook` files relative to the module…
Such as the `config.js`, `middleware.js`, etc. It appears to work fine now all the `@storybook` modules at the root. Perhaps that logic changed with the 3.4.0 rc?

**Comment by davideschiera** [comment]
At least in my environment/configuration (v4.0.0-alpha.10), `start-storybook` went from one core at 100% to ~0% installing [`fsevents`](https://www.npmjs.com/package/fsevents) as mentioned in https://github.com/webpack/webpack/issues/701.

**Comment by levilansing** [comment]
`rm -rf node-modules && npm i`

Just had this exact issue. Storybooks v3 though I doubt it's related to Storybooks. `rm -rf node-modules && npm i` did the trick for me. I'd believe it's related to fsevents, but I did a clean npm install first. The issue started after installing/uninstalling a bunch of node modules.
