### ISSUE TITLE
Resolve.modules not finding files

### ISSUE THREAD

**Issue by fionnbharra** [storybooks/react-storybook#758]
I'm trying to use a custom webpack config which includes [resolve.modules](https://webpack.js.org/configuration/resolve/#resolve-modules)

My .storybook/webpack.config.js looks like this - 

```
const path = require('path');

module.exports = {
  resolve: {
    modules: [
      'src',
      'node_modules',
    ],
    extensions: ['.json', '.js'],
  },
}
```

When I `npm run storybook` I get multiple errors similar to this -  
```
Cannot resolve 'file' or 'directory' /Users/fionnbharra/workspaces/webpack-storybook/node_modules/@kadira/storybook/dist/server/addons.js in /Users/fionnbharra/workspaces/webpack-storybook
```

Is it possible to use resolve.modules with storybooks?

**Comment by danielduan** [comment]
`resolve.modules` is a webpack 2 feature. if you're using storybooks@2.35.3, that uses webpack 1 which has different `resolve.root`, `resolve.fallback`, etc. There's plans for an upcoming release with support for wp2 soon though.

**Comment by ndelangen** [comment]
This will become possible with 3.0.0

**Comment by fionnbharra** [comment]
Thanks!

**Comment by Sashkan** [comment]
Sheesh, glad to find this. Spared me a lot of time ! So, there's actually no way to use this resolve until v3 is released ?

**Comment by ndelangen** [comment]
Storybook 2.x.x uses webpack 1. And it does allow you to provide a completely custom webpack config.

So you can use anything that's in the webpack 1 config options:
http://webpack.github.io/docs/resolving.html

I hope this helps you.

**Comment by ajfarkas** [comment]
So, does Storybook 3 actually use Webpack 2?
I still see this issue with 3.3.15, and TBH the documentation here is… disappointing.

**Comment by danielduan** [comment]
Yes, Storybook 3 uses Webpack 2 and now Webpack 3.

If you're not able to get your files resolving correctly, you should take a look at the Webpack documentation instead. While we try our best to document different use cases, it's hard to cover every usage scenario in Webpack.

You can create a new ticket with your config and perhaps someone can help you debug.

**Comment by ajfarkas** [comment]
What I'm asking is: what are you doing with Webpack? I can read through your code, but the reason for documentation is that I don't have to.

Webpack obviously works with my webapp, so there's something I'm missing about how Storybook is using Webpack that makes my config break. That won't be on the Webpack documentation.

I'm just looking for an entry point to do my own debugging.

**Comment by danielduan** [comment]
The default webpack config is here for react: https://github.com/storybooks/storybook/blob/master/app/react/src/server/config/webpack.config.js

You will need to use the extend mode or the full control mode in the docs to modify or override the defaults.
