### ISSUE TITLE
@kadira/storybook-addon-options failing with npm login issue

### ISSUE THREAD

**Issue by abhijeetNmishra** [storybooks/react-storybook#761]
I am able to successfully install @kadira/storybook but failing for addons like @kadira/storybook-addon-options.

We have a private artifactory from where we are installing private package. Due to this, we have our project specific .npmrc file like 

```
ca=
@kadira:registry=https://registry.npmjs.org
```

and global npmrc has entry 
```
ca=
@kadira:registry=https://replicate.npmjs.com
```

Any idea what i need to do to resolve this scoped package installation.

**Comment by ndelangen** [comment]
This sounds like a support question for npm or artifactory.

If the package `@kadira/storybook` works,
why wouldn't `@kadira/storybook-addon-options` ? How exactly is is failing?

**Comment by abhijeetNmishra** [comment]
I got it working by removing always_auth = true from project specific .npmrc file and moving it to package.json. Closing this 👍
